2024-02-24 22:38:25,572 amazon INFO     success
2024-02-24 22:38:58,299 amazon INFO     success
2024-02-29 13:35:52,387 amazon INFO     success
2024-02-29 13:37:10,128 amazon INFO     success
2024-02-29 15:37:44,884 amazon INFO     success
2024-02-29 15:58:53,928 amazon INFO     success
2024-02-29 16:52:29,333 amazon INFO     success
2024-02-29 17:13:18,507 amazon INFO     success
2024-02-29 17:14:06,731 amazon INFO     success
2024-02-29 17:14:35,251 amazon INFO     success
2024-03-01 11:18:46,067 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '1'
2024-03-01 11:20:12,219 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:13,721 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:14,324 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:14,565 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:14,840 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:15,104 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:15,339 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:20:15,777 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:21:55,343 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:21:55,912 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:21:57,344 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:23:37,971 amazon INFO     success
2024-03-01 11:25:19,560 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 43, in pass_otp_string
    status = ordering_object_id_wise_dict[ordering_object_id].pass_otp_string(otp_string=otp_string)
KeyError: 0
2024-03-01 11:31:45,908 amazon INFO     success
2024-03-01 11:39:30,284 amazon INFO     success
2024-03-01 11:44:13,107 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:44:14,978 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:44:15,492 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:44:15,694 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:44:15,854 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:45:26,667 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:45:27,302 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:45:27,464 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:45:27,675 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '0'
2024-03-01 11:45:46,540 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:45:47,429 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:45:47,597 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:45:47,775 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:45:58,576 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:46:00,120 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: '2'
2024-03-01 11:54:09,954 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:11,569 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:11,720 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:11,935 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,091 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,257 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,416 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,625 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,813 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:12,995 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:45,758 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:46,342 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:54:46,511 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 33, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 0
2024-03-01 11:58:09,005 amazon INFO     success
2024-03-01 11:58:27,647 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 31, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
NameError: name 'ordering_object_id_wise_dict' is not defined
2024-03-01 11:58:28,482 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 31, in get_order_status
    status = ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
NameError: name 'ordering_object_id_wise_dict' is not defined
2024-03-01 12:00:23,680 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 31, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
NameError: name 'ordering_object_id_wise_dict' is not defined
2024-03-01 12:01:16,781 amazon ERROR    error
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 31, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 1
2024-03-01 12:05:05,091 amazon INFO     success
2024-03-01 12:08:01,845 amazon INFO     success
2024-03-01 12:20:01,060 amazon INFO     success
2024-03-01 13:31:36,926 amazon INFO     success
2024-03-01 13:48:16,609 amazon ERROR    Exception in Get Order Status: 2
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 37, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 2
2024-03-01 13:48:21,311 amazon ERROR    Exception in Get Order Status: 3
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 37, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 3
2024-03-01 13:51:12,693 amazon INFO     success
2024-03-01 13:51:16,743 amazon ERROR    Exception in Get Order Status: 3
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 37, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 3
2024-03-01 14:11:19,807 amazon INFO     success
2024-03-01 14:12:02,554 amazon ERROR    Exception in Get Order Status: 2
Traceback (most recent call last):
  File "/home/dhruv/ordering_automation/endpoints/amazon_automation.py", line 37, in get_order_status
    status = constants.ordering_object_id_wise_dict[ordering_object_id].get_ordering_process_status()
KeyError: 2
2024-03-01 14:24:02,190 amazon INFO     success
2024-03-01 14:29:42,817 amazon INFO     success
2024-03-01 14:30:42,941 amazon INFO     success
2024-03-01 14:31:43,887 amazon INFO     success
2024-03-01 14:33:11,528 amazon INFO     success
2024-03-01 14:34:40,333 amazon INFO     success
2024-03-01 17:01:12,293 amazon INFO     success
2024-03-01 17:07:03,035 amazon INFO     success
2024-03-01 17:14:30,983 amazon INFO     success
